username = input("Please tell me your name ")
username1 = str.strip(username)
print(username1)
username2 = str.capitalize(username1)
print(username2)
username3 = len(username2)
print(username3)
username4 = reversed(username2)
print(list(username4))
